--liquibase formatted sql
CREATE TABLE sensor (
                        id int generated always as identity primary key,
                        sensor_name VARCHAR(100) NOT NULL unique
);

CREATE TABLE measurement (
                             measurement_id int generated by default as identity primary key ,
                             sensor_id int references sensor(id),
                             measurement VARCHAR NOT NULL,
                             temperature float not null,
                             raining bool not null,
                             created_date date default current_date
);

